import type { Film } from "./types"

export const filmData: Film[] = [
  {
    id: 115,
    slug: "stalker",
    title: "Stalker",
    title_locale: "en-US",
    original_title: "Сталкер",
    year: 1979,
    duration: 162,
    stills: {
      small: "https://assets.mubicdn.net/images/film/115/image-w256.jpg?1677692554",
      medium: "https://assets.mubicdn.net/images/film/115/image-w448.jpg?1677692554",
      standard: "https://assets.mubicdn.net/images/film/115/image-w856.jpg?1677692554",
      retina: "https://assets.mubicdn.net/images/film/115/image-w1280.jpg?1677692554",
      small_overlaid: "https://assets.mubicdn.net/images/film/115/image-w512_overlaid.jpg?1677692554",
      large_overlaid: "https://assets.mubicdn.net/images/film/115/image-w1504_overlaid.jpg?1677692554",
    },
    still_focal_point: {
      x: 0.423398,
      y: 0.405941,
    },
    hd: true,
    average_colour_hex: "7B8F7F",
    trailer_url: "https://trailers.mubicdn.net/115/t-stalker_en_us_671.123_1280_720_1579678696.mp4",
    trailer_id: 7399,
    popularity: 10658,
    web_url: "https://mubi.com/films/stalker",
    genres: ["Drama", "Vanguarda", "Ficção Científica"],
    average_rating: 4.6,
    average_rating_out_of_ten: 9.2,
    number_of_ratings: 17795,
    mubi_release: false,
    should_use_safe_still: false,
    still_url: "https://images.mubicdn.net/images/film/115/cache-859009-1677692554/image-w1280.jpg",
    title_upcase: "STALKER",
    critic_review_rating: 5,
    content_rating: {
      label: "caution",
      rating_code: "ATENÇÃO",
      description: "Contém material que pode não ser adequado para crianças ou jovens.",
      icon_url: null,
      label_hex_color: "e05d04",
    },
    short_synopsis:
      'Um homem lidera uma expedição através de um deserto perigoso em busca da "sala", um lugar que tem a reputação de ser capaz de satisfazer os desejos mais profundos de uma pessoa.',
    short_synopsis_html:
      "<p>Um homem lidera uma expedição através de um deserto perigoso em busca da &#8220;sala&#8221;, um lugar que tem a reputação de ser capaz de satisfazer os desejos mais profundos de uma pessoa.</p>",
    episode: null,
    historic_countries: ["União Soviética", "Alemanha Ocidental"],
    portrait_image: null,
    title_treatment_url: null,
    default_editorial:
      "Hailed as one of the greatest films of all time, Andrei Tarkovsky's mesmerizing opus is striking in its sepia palette, and staggering in its thematic and metaphysical weight. A profound post-apocalyptic grail story whose vision of ecological degradation and moral decay remains startlingly prescient.",
    default_editorial_html:
      "<p>Hailed as one of the greatest films of all time, Andrei Tarkovsky&#8217;s mesmerizing opus is striking in its sepia palette, and staggering in its thematic and metaphysical weight. A profound post-apocalyptic grail story whose vision of ecological degradation and moral decay remains startlingly prescient.</p>",
    cast_members_count: 30,
    industry_events_count: 17,
    comments_count: 588,
    mubi_go_highlighted: false,
    optimised_trailers: [
      {
        url: "https://trailers.mubicdn.net/115/optimised/240p-t-stalker_en_us_671.123_1280_720_1579678696.mp4",
        profile: "240p",
      },
      {
        url: "https://trailers.mubicdn.net/115/optimised/720p-t-stalker_en_us_671.123_1280_720_1579678696.mp4",
        profile: "720p",
      },
    ],
    directors: [
      {
        name: "Andrei Tarkovsky",
        name_upcase: "ANDREI TARKOVSKY",
        slug: "andrei-tarkovsky",
      },
    ],
    consumable: null,
    press_quote: null,
    star_rating: null,
    award: null,
    experiment_stills: null,
    content_warnings: [
      {
        id: 3,
        name: "automutilação",
        key: "self_harm",
      },
      {
        id: 6,
        name: "conteúdo sexual gráfico",
        key: "graphic_sexual_content",
      },
    ],
    artworks: [
      {
        format: "tile_artwork",
        locale: null,
        image_url: "https://assets.mubicdn.net/images/artworks/531013/images-original.png?1680022319",
      },
      {
        format: "cover_artwork_box_episode",
        locale: null,
        image_url: "https://assets.mubicdn.net/images/artworks/531014/images-original.png?1680022324",
      },
    ],
    highlighted_industry_event_entry: null,
  },
  {
    id: 114,
    slug: "oldboy",
    title: "Oldboy",
    title_locale: "pt-BR",
    original_title: "올드보이",
    year: 2003,
    duration: 120,
    stills: {
      small: "https://assets.mubicdn.net/images/film/114/image-w256.jpg?1666951909",
      medium: "https://assets.mubicdn.net/images/film/114/image-w448.jpg?1666951909",
      standard: "https://assets.mubicdn.net/images/film/114/image-w856.jpg?1666951909",
      retina: "https://assets.mubicdn.net/images/film/114/image-w1280.jpg?1666951909",
      small_overlaid: "https://assets.mubicdn.net/images/film/114/image-w512_overlaid.jpg?1666951909",
      large_overlaid: "https://assets.mubicdn.net/images/film/114/image-w1504_overlaid.jpg?1666951909",
    },
    still_focal_point: {
      x: 0.532775,
      y: 0.428218,
    },
    hd: true,
    average_colour_hex: "5C464A",
    trailer_url: "https://trailers.mubicdn.net/114/t-oldboy_pt_br_20785.776_3840_2160_1708405003.mp4",
    trailer_id: 102382,
    popularity: 20536,
    web_url: "https://mubi.com/films/oldboy",
    genres: ["Drama", "Suspense", "Mistério", "Ação"],
    average_rating: 4.4,
    average_rating_out_of_ten: 8.8,
    number_of_ratings: 52316,
    mubi_release: false,
    should_use_safe_still: false,
    still_url: "https://images.mubicdn.net/images/film/114/cache-826019-1666951909/image-w1280.jpg",
    title_upcase: "OLDBOY",
    critic_review_rating: 4.416666666666667,
    content_rating: {
      label: "mature",
      rating_code: "MADURO",
      description: "Contém material e temas adequados somente para audiências maduras.",
      icon_url: null,
      label_hex_color: "dd2323",
    },
    short_synopsis:
      "Aprisionado por um captor sádico por 15 anos, Oh Dae-su sobrevive apenas devido à sua determinação de se vingar do vilão que tornou sua vida um inferno. Mas quando é subitamente libertado sem explicação, ele embarca em uma busca por vingança e se vê envolvido em uma conspiração kafkiana.",
    short_synopsis_html:
      "<p>Aprisionado por um captor sádico por 15 anos, Oh Dae-su sobrevive apenas devido à sua determinação de se vingar do vilão que tornou sua vida um inferno. Mas quando é subitamente libertado sem explicação, ele embarca em uma busca por vingança e se vê envolvido em uma conspiração kafkiana.</p>",
    episode: null,
    historic_countries: ["Coreia do Sul"],
    portrait_image: null,
    title_treatment_url: null,
    default_editorial:
      "Um dos maiores sucessos internacionais dos anos 2000, esta saga de vingança extrema e muito surreal ganhou merecidamente o Grande Prêmio em Cannes em 2004. Amplificando a proeminência global do mestre sul-coreano Park Chan-wook, Oldboy tem uma energia que impressiona o mundo todo.",
    default_editorial_html:
      "<p>Um dos maiores sucessos internacionais dos anos 2000, esta saga de vingança extrema e muito surreal ganhou merecidamente o Grande Prêmio em Cannes em 2004. Amplificando a proeminência global do mestre sul-coreano Park Chan-wook, <em>Oldboy</em> tem uma energia que impressiona o mundo todo.</p>",
    cast_members_count: 30,
    industry_events_count: 43,
    comments_count: 1013,
    mubi_go_highlighted: false,
    optimised_trailers: [
      {
        url: "https://trailers.mubicdn.net/114/optimised/240p-t-oldboy_pt_br_20785.776_3840_2160_1708405003.mp4",
        profile: "240p",
      },
      {
        url: "https://trailers.mubicdn.net/114/optimised/720p-t-oldboy_pt_br_20785.776_3840_2160_1708405003.mp4",
        profile: "720p",
      },
      {
        url: "https://trailers.mubicdn.net/114/optimised/1080p-t-oldboy_pt_br_20785.776_3840_2160_1708405003.mp4",
        profile: "1080p",
      },
    ],
    directors: [
      {
        name: "Park Chan-wook",
        name_upcase: "PARK CHAN-WOOK",
        slug: "park-chan-wook",
      },
    ],
    consumable: null,
    press_quote: null,
    star_rating: null,
    award: null,
    experiment_stills: null,
    content_warnings: [
      {
        id: 1,
        name: "agressão sexual",
        key: "sexual_assault",
      },
      {
        id: 3,
        name: "automutilação",
        key: "self_harm",
      },
    ],
    artworks: [
      {
        format: "tile_artwork",
        locale: null,
        image_url: "https://assets.mubicdn.net/images/artworks/491300/images-original.png?1666951877",
      },
    ],
    highlighted_industry_event_entry: {
      id: 2851,
      year: 2004,
      status: "won",
      display_text: "Prêmio do Júri",
      full_display_text: "2004 | Vencedor: Prêmio do Júri",
      industry_event: {
        id: 1,
        name: "Cannes Film Festival",
        slug: "cannes",
        type: "festival",
        logo_url: "https://images.mubicdn.net/images/industry_event/1/cache-222790-1494527057/logo-small_black.png",
        white_logo_url:
          "https://images.mubicdn.net/images/industry_event/1/cache-222790-1494527057/logo-large_white.png",
        cover_url: "https://images.mubicdn.net/images/industry_event/1/cache-222788-1494406355/cover-original.jpg",
      },
    },
  },
  {
    id: 1537,
    slug: "apocalypse-now",
    title: "Apocalypse Now",
    title_locale: "pt-BR",
    original_title: "Apocalypse Now (Theatrical Cut)",
    year: 1979,
    duration: 153,
    stills: {
      small: "https://assets.mubicdn.net/images/film/1537/image-w256.jpg?1711623742",
      medium: "https://assets.mubicdn.net/images/film/1537/image-w448.jpg?1711623742",
      standard: "https://assets.mubicdn.net/images/film/1537/image-w856.jpg?1711623742",
      retina: "https://assets.mubicdn.net/images/film/1537/image-w1280.jpg?1711623742",
      small_overlaid: "https://assets.mubicdn.net/images/film/1537/image-w512_overlaid.jpg?1711623742",
      large_overlaid: "https://assets.mubicdn.net/images/film/1537/image-w1504_overlaid.jpg?1711623742",
    },
    still_focal_point: {
      x: 0.504178,
      y: 0.643564,
    },
    hd: true,
    average_colour_hex: "414444",
    trailer_url: "https://trailers.mubicdn.net/1537/t-apocalypse-now_en_us_1920_1080_1683140076.mp4",
    trailer_id: 7748,
    popularity: 15412,
    web_url: "https://mubi.com/films/apocalypse-now",
    genres: ["Drama", "Guerra", "Mistério"],
    average_rating: 4.5,
    average_rating_out_of_ten: 9,
    number_of_ratings: 33094,
    mubi_release: false,
    should_use_safe_still: false,
    still_url: "https://images.mubicdn.net/images/film/1537/cache-29806-1711623742/image-w1280.jpg",
    title_upcase: "APOCALYPSE NOW",
    critic_review_rating: 5,
    content_rating: {
      label: "mature",
      rating_code: "MADURO",
      description: "Contém material e temas adequados somente para audiências maduras.",
      icon_url: null,
      label_hex_color: "dd2323",
    },
    short_synopsis:
      "Vietnã, 1970. O capitão Willard tenciona matar o coronel Kurtz, um oficial outrora promissor que enlouqueceu completamente. Na companhia de um barco-patrulha da Marinha cheio de rapazes sagazes, um oficial da Cavalaria Aérea e um fotojornalista, Willard se aventura em território inimigo.",
    short_synopsis_html:
      "<p>Vietnã, 1970. O capitão Willard tenciona matar o coronel Kurtz, um oficial outrora promissor que enlouqueceu completamente. Na companhia de um barco-patrulha da Marinha cheio de rapazes sagazes, um oficial da Cavalaria Aérea e um fotojornalista, Willard se aventura em território inimigo.</p>",
    episode: null,
    historic_countries: ["Estados Unidos"],
    portrait_image: null,
    title_treatment_url: null,
    default_editorial:
      '"My film is not about Vietnam. It is Vietnam," said Francis Ford Coppola of his visionary, Palme d\'Or-winning adaptation of Heart of Darkness. With a mythic, truly unforgettable appearance by Marlon Brando, Apocalypse Now traces a visceral descent into madness to comment on the folly of war.',
    default_editorial_html:
      "<p>&#8220;My film is not about Vietnam. It is Vietnam,&#8221; said Francis Ford Coppola of his visionary, Palme d&#8217;Or-winning adaptation of <em>Heart of Darkness</em>. With a mythic, truly unforgettable appearance by Marlon Brando, <em>Apocalypse Now</em> traces a visceral descent into madness to comment on the folly of war.</p>",
    cast_members_count: 25,
    industry_events_count: 27,
    comments_count: 522,
    mubi_go_highlighted: false,
    optimised_trailers: [
      {
        url: "https://trailers.mubicdn.net/1537/optimised/240p-t-apocalypse-now_en_us_1920_1080_1683140076.mp4",
        profile: "240p",
      },
      {
        url: "https://trailers.mubicdn.net/1537/optimised/720p-t-apocalypse-now_en_us_1920_1080_1683140076.mp4",
        profile: "720p",
      },
    ],
    directors: [
      {
        name: "Francis Ford Coppola",
        name_upcase: "FRANCIS FORD COPPOLA",
        slug: "francis-ford-coppola",
      },
    ],
    consumable: null,
    press_quote: null,
    star_rating: null,
    award: null,
    experiment_stills: null,
    content_warnings: [
      {
        id: 3,
        name: "automutilação",
        key: "self_harm",
      },
      {
        id: 4,
        name: "crueldade animal",
        key: "animal_cruelty",
      },
    ],
    artworks: [
      {
        format: "tile_artwork",
        locale: null,
        image_url: "https://assets.mubicdn.net/images/artworks/675941/images-original.png?1712073512",
      },
    ],
    highlighted_industry_event_entry: {
      id: 1113,
      year: 1979,
      status: "won",
      display_text: "Palma de Ouro",
      full_display_text: "1979 | Vencedor: Palma de Ouro",
      industry_event: {
        id: 1,
        name: "Cannes Film Festival",
        slug: "cannes",
        type: "festival",
        logo_url: "https://images.mubicdn.net/images/industry_event/1/cache-222790-1494527057/logo-small_black.png",
        white_logo_url:
          "https://images.mubicdn.net/images/industry_event/1/cache-222790-1494527057/logo-large_white.png",
        cover_url: "https://images.mubicdn.net/images/industry_event/1/cache-222788-1494406355/cover-original.jpg",
      },
    },
  },
  {
    id: 362266,
    slug: "monster-2023",
    title: "Monstro",
    title_locale: "pt-BR",
    original_title: "Kaibutsu | 怪物",
    year: 2023,
    duration: 121,
    stills: {
      small: "https://assets.mubicdn.net/images/film/362266/image-w256.jpg?1717513634",
      medium: "https://assets.mubicdn.net/images/film/362266/image-w448.jpg?1717513634",
      standard: "https://assets.mubicdn.net/images/film/362266/image-w856.jpg?1717513634",
      retina: "https://assets.mubicdn.net/images/film/362266/image-w1280.jpg?1717513634",
      small_overlaid: "https://assets.mubicdn.net/images/film/362266/image-w512_overlaid.jpg?1717513634",
      large_overlaid: "https://assets.mubicdn.net/images/film/362266/image-w1504_overlaid.jpg?1717513634",
    },
    still_focal_point: {
      x: 0.533426,
      y: 0.362963,
    },
    hd: true,
    average_colour_hex: "456458",
    trailer_url: "https://trailers.mubicdn.net/362266/t-monster-2023_pt_br_2763.4809999999998_1920_1080_1699662910.mp4",
    trailer_id: 97247,
    popularity: 7557,
    web_url: "https://mubi.com/films/monster-2023",
    genres: ["Drama", "LGBTQ+"],
    average_rating: 4.6,
    average_rating_out_of_ten: 9.2,
    number_of_ratings: 17852,
    mubi_release: false,
    should_use_safe_still: false,
    still_url: "https://images.mubicdn.net/images/film/362266/cache-831801-1717513634/image-w1280.jpg",
    title_upcase: "MONSTRO",
    critic_review_rating: 3.6785714285714284,
    content_rating: {
      label: "caution",
      rating_code: "ATENÇÃO",
      description: "Contém material que pode não ser adequado para crianças ou jovens.",
      icon_url: null,
      label_hex_color: "e05d04",
    },
    short_synopsis:
      "When a young boy displays increasingly worrying behavior at school and home, his mother decides to discuss it with his teachers. It soon becomes apparent that one of his teachers is the source of all the problems. But as the mystery unfolds, the truth becomes more complex than expected.",
    short_synopsis_html:
      "<p>When a young boy displays increasingly worrying behavior at school and home, his mother decides to discuss it with his teachers. It soon becomes apparent that one of his teachers is the source of all the problems. But as the mystery unfolds, the truth becomes more complex than expected.</p>",
    episode: null,
    historic_countries: ["Japão"],
    portrait_image: null,
    title_treatment_url: null,
    default_editorial:
      "Winner of the Queer Palm and Best Screenplay at Cannes, Hirokazu Kore-eda's intricately structured drama delves into the fragility of boyhood. Bookended by fires and storms, delicate feelings of anger, confusion, and love swell through an exquisite final score from the late maestro Ryuichi Sakamoto.",
    default_editorial_html:
      "<p>Winner of the Queer Palm and Best Screenplay at Cannes, Hirokazu Kore-eda&#8217;s intricately structured drama delves into the fragility of boyhood. Bookended by fires and storms, delicate feelings of anger, confusion, and love swell through an exquisite final score from the late maestro Ryuichi Sakamoto.</p>",
    cast_members_count: 25,
    industry_events_count: 56,
    comments_count: 343,
    mubi_go_highlighted: false,
    optimised_trailers: [
      {
        url: "https://trailers.mubicdn.net/362266/optimised/240p-t-monster-2023_pt_br_2763.4809999999998_1920_1080_1699662910.mp4",
        profile: "240p",
      },
      {
        url: "https://trailers.mubicdn.net/362266/optimised/720p-t-monster-2023_pt_br_2763.4809999999998_1920_1080_1699662910.mp4",
        profile: "720p",
      },
    ],
    directors: [
      {
        name: "Hirokazu Koreeda",
        name_upcase: "HIROKAZU KOREEDA",
        slug: "hirokazu-koreeda",
      },
    ],
    consumable: null,
    press_quote: null,
    star_rating: null,
    award: null,
    experiment_stills: null,
    content_warnings: [
      {
        id: 2,
        name: "violência doméstica",
        key: "domestic_violence",
      },
      {
        id: 3,
        name: "automutilação",
        key: "self_harm",
      },
    ],
    artworks: [
      {
        format: "tile_artwork",
        locale: null,
        image_url: "https://assets.mubicdn.net/images/artworks/690581/images-original.png?1717520272",
      },
    ],
    highlighted_industry_event_entry: {
      id: 438389,
      year: 2023,
      status: "won",
      display_text: "Melhor Roteiro",
      full_display_text: "2023 | Vencedor: Melhor Roteiro",
      industry_event: {
        id: 1,
        name: "Cannes Film Festival",
        slug: "cannes",
        type: "festival",
        logo_url: "https://images.mubicdn.net/images/industry_event/1/cache-222790-1494527057/logo-small_black.png",
        white_logo_url:
          "https://images.mubicdn.net/images/industry_event/1/cache-222790-1494527057/logo-large_white.png",
        cover_url: "https://images.mubicdn.net/images/industry_event/1/cache-222788-1494406355/cover-original.jpg",
      },
    },
  },
]

